version: "3.9"
name: cs_bingo


services:
  nginx:
    image: nginx

    ports:
      - "8000:80"

    extra_hosts:
      - "host.docker.internal:host-gateway"

    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf

    restart: always

  app:
    build:
      dockerfile: dev/Dockerfile
      context: ..

    environment:
      SECRET_KEY: "********************************"
      PG_PASS: "0000"

    volumes:
      - ./../app:/app

    ports:
      - "8080:8080"

    depends_on:
      - nginx
      - db

    command: python main.py
    restart: always

  db:
    image: postgres

    environment:
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: cs_bingo

    ports:
      - "5432:5432"

    volumes:
      - db_data:/var/lib/postgresql/data/

    restart: always

  redis:
    image: redis
    restart: always


volumes:
    db_data:
