FROM python:3.9-slim-buster

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ENV TZ='UTC'
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y wait-for-it

COPY app/requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY deploy/entrypoint.sh /entrypoint.sh
RUN chmod -R 755 /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

COPY app /app
WORKDIR /app
