version: "3.9"


services:
  front:
    image: registry.dezz.space/cs_bingo:latest

    networks:
      hub:

    deploy:
      update_config:
        order: start-first


networks:
  hub:
    name: hub
    external: true
