version: "3.9"


services:
  back:
    image: registry.dezz.space/cs_bingo/back:latest

    environment:
      PG_PASS: ${PG_PASS}
      SECRET_KEY: ${SECRET_KEY}

    networks:
      hub:
      postgres:

    deploy:
      update_config:
        order: start-first

  front:
    image: registry.dezz.space/cs_bingo/front:latest

    networks:
      hub:

    deploy:
      update_config:
        order: start-first


networks:
  hub:
    name: hub
    external: true

  postgres:
    name: postgres
    external: true
