version: "3.9"


services:
  back:
    image: registry.dezz.space/cs_bingo/back:latest

    environment:
      PG_PASS: ${PG_PASS}
      SECRET_KEY: ${SECRET_KEY}

    networks:
      postgres:

    deploy:
      update_config:
        order: start-first

    command: ["migrate"]


networks:
  postgres:
    name: postgres
    external: true
